apiVersion: v1
kind: Namespace
metadata:
  name: landscape-trial
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: landscape-trial
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth:admin-role:landscape-trial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth:admin-role
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: landscape-trial
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: trial
  namespace: landscape-trial
  labels:
    app: trial
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - name: trial
          image: dirigiblelabs/dirigible-keycloak
          ports:
            - containerPort: 8080
          env:
            - name: DIRIGIBLE_THEME_DEFAULT
              value: "fiori"
            - name: KEYCLOAK_CONFIDENTIAL_PORT
              value: "443"
            - name: KEYCLOAK_SSL_REQUIRED
              value: "none"
            - name: KEYCLOAK_CLIENT_ID
              value: "trial"
            - name: KEYCLOAK_REALM
              value: "landscape-trial"
            # Replace the placeholder with your domain name (e.g. ingress.dev.blog.shoot.canary.k8s-hana.ondemand.com)
            - name: KEYCLOAK_AUTH_SERVER_URL
              value: "https://auth.<your-domain-name>/auth"
---
apiVersion: v1
kind: Service
metadata:
  name: trial
  namespace: landscape-trial
  labels:
    app: trial
spec:
  ports:
  - port: 8080
  type: ClusterIP
  selector:
    app: trial
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
  name: trial
  namespace: landscape-trial
spec:
  tls:
  # Replace the placeholder with your domain name (e.g. ingress.dev.blog.shoot.canary.k8s-hana.ondemand.com)
  - hosts:
    - trial.<your-domain-name>
    secretName: trial-certificate
  rules:
    # Replace the placeholder with your domain name (e.g. ingress.dev.blog.shoot.canary.k8s-hana.ondemand.com)
    - host: trial.<your-domain-name>
      http:
        paths:
          - path: /
            backend:
              serviceName: trial
              servicePort: 8080
