apiVersion: v1
kind: Namespace
metadata:
  name: zeus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: zeus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth:admin-role:zeus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth:admin-role
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: zeus
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zeus-database
  namespace: zeus
spec:
  serviceName: zeus-database-jdbc
  replicas: 1
  template:
    metadata:
      labels:
        app: zeus-database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: zeus-database
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: root
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "2"
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: zeus
            - name: POSTGRES_PASSWORD
              value: zeus
      serviceAccountName: service-account
  volumeClaimTemplates:
    - metadata:
        name: root
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zeus-database-jdbc
  namespace: zeus
  labels:
    app: zeus-database
spec:
  ports:
  - port: 5432
  type: ClusterIP
  selector:
    app: zeus-database
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zeus
  namespace: zeus
  labels:
    app: zeus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zeus
  template:
    metadata:
      labels:
        app: zeus
    spec:
      containers:
        - name: zeus
          image: dirigiblelabs/zeus
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          env:
            - name: "DIRIGIBLE_HOME_URL"
              value: "/services/v3/web/zeus/"
            - name: "DIRIGIBLE_THEME_DEFAULT"
              value: "fiori"
            - name: KEYCLOAK_CONFIDENTIAL_PORT
              value: "443"
            - name: KEYCLOAK_SSL_REQUIRED
              value: "none"
            - name: KEYCLOAK_CLIENT_ID
              value: "admin"
            - name: KEYCLOAK_REALM
              value: "zeus"
            - name: KEYCLOAK_AUTH_SERVER_URL
              # Replace the placeholder with your domain name (e.g. ingress.dev.blog.shoot.canary.k8s-hana.ondemand.com)
              value: "https://auth.<your-domain-name>/auth"
            - name: DIRIGIBLE_DATABASE_PROVIDER
              value: "custom"
            - name: DIRIGIBLE_DATABASE_CUSTOM_DATASOURCES
              value: "POSTGRES"
            - name: DIRIGIBLE_DATABASE_DATASOURCE_NAME_DEFAULT
              value: "POSTGRES"
            - name: POSTGRES_DRIVER
              value: "org.postgresql.Driver"
            - name: POSTGRES_URL
              value: "jdbc:postgresql://zeus-database-jdbc:5432/zeus"
            - name: POSTGRES_USERNAME
              # The PostgreSQL user
              value: "zeus"
            - name: POSTGRES_PASSWORD
              # The PostgreSQL user's password
              value: "zeus"
            - name: DIRIGIBLE_SCHEDULER_DATABASE_DRIVER
              value: "org.postgresql.Driver"
            - name: DIRIGIBLE_SCHEDULER_DATABASE_URL
              value: "jdbc:postgresql://zeus-database-jdbc:5432/zeus"
            - name: DIRIGIBLE_SCHEDULER_DATABASE_USER
              # The PostgreSQL user
              value: "zeus"
            - name: DIRIGIBLE_SCHEDULER_DATABASE_PASSWORD
              # The PostgreSQL user's password
              value: "zeus"
            - name: DIRIGIBLE_SCHEDULER_DATABASE_DELEGATE
              value: "org.quartz.impl.jdbcjobstore.PostgreSQLDelegate"
            - name: DIRIGIBLE_MESSAGING_USE_DEFAULT_DATABASE
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: zeus
  namespace: zeus
  labels:
    app: zeus
spec:
  ports:
  - port: 8080
  type: ClusterIP
  selector:
    app: zeus
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: "nginx"
  name: zeus
  namespace: zeus
spec:
  tls:
  # Replace the placeholder with your domain name (e.g. ingress.dev.blog.shoot.canary.k8s-hana.ondemand.com)
  - hosts:
    - zeus.<your-domain-name>
    secretName: zeus-certificate
  rules:
    # Replace the placeholder with your domain name (e.g. ingress.dev.blog.shoot.canary.k8s-hana.ondemand.com)
    - host: zeus.<your-domain-name>
      http:
        paths:
          - path: /
            backend:
              serviceName: zeus
              servicePort: 8080
